export type FormData = {
  name: string;
  cuisineType: string;
  priceForTwo: number;
  images: string;
  pinCode: number;
  agreementUrl?: string;
  facilities: string[];
  description: string[];
  openingTime: string;
  closingTime: string;
  mapLink: string;
  phoneNumber: string;
  streetName: string;
  houseNo: string;
  area: string;
  city: string;
  lat: number;
  long: number;
  address: string;
  totalPersons: number;
};
